In [1]:
from sklearn import tree
from sklearn import svm
from sklearn import ensemble
from sklearn import neighbors
from sklearn import linear_model
from sklearn import metrics
from sklearn import preprocessing

In [2]:
%matplotlib inline 

from IPython.display import Image
import matplotlib as mlp
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import sklearn
import seaborn as sns

In [3]:
#df = pd.read_csv('../input/mytest.csv')
df = pd.read_csv("C:\\Users\Blessy Rose\Downloads\dataset_website.csv")

print (df.shape)

#df.dtypes

(11055, 32)


In [5]:
# Load data
df.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [7]:
#Spliting data as independent and dependent 
#Removing index coloumn in independent dataset
x=df.iloc[:,1:31].values
y=df.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


In [8]:
#Splitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train, x_test,y_train,y_test )

[[ 1 -1  1 ...  1  1  1]
 [ 1  1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1 -1]
 ...
 [-1  1  1 ...  1  1  1]
 [-1 -1  1 ...  1  1  1]
 [ 1 -1  1 ...  1  1  1]] [[ 1 -1  1 ...  1  0  1]
 [ 1 -1  1 ...  1  0  1]
 [ 1 -1  1 ...  1  1  1]
 ...
 [-1 -1  1 ...  1  1  1]
 [ 1 -1  1 ...  1  0  1]
 [ 1 -1  1 ...  1  1  1]] [ 1 -1 -1 ...  1 -1 -1] [-1 -1 -1 ...  1  1  1]
